{{- if .Values.persistentVolume }}
apiVersion: v1
kind: PersistentVolume
metadata:
  name: {{ include "hello-helm.fullname" . }}
  labels:
    {{- include "hello-helm.labels" . | nindent 4 }}
spec:
  claimRef:
    name: {{ include "hello-helm.fullname" . }}
  hostPath:
    path: "/mnt/data"
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi
{{- end }}
